PRNGSeed: 0

data:
  fourier:
    max_freq: 5
    num_bands: 50
    base: 2
  generate:
    length_scale: 0.1
    num_train: 100
    num_draw: 100
    xlim: [0,1]

model:
  output_sizes: [512, 1]

hypermodel:
  hidden_layers: [100]

varinf:
  data_std: 0.01
  init_std: 1
  prior:
    pi: 0
    small_std: 0.01
    big_std: 2

train:
  num_epochs: 99
  print_epoch_loss: 1
  lr: 1e-2
  batch_size: 2