PRNGSeed: 2

data:
  fourier:
    max_freq: 5
    num_bands: 100
    base: 2
  generate:
    length_scale: 0.1
    num_train: 300
    num_draw: 100
    xlim: [0,1]

model:
  output_sizes: [256, 1]
  activation: 'leaky relu'

varinf:
  data_std: 0.005
  init_std: 1
  prior:
    pi: 0.5
    small_std: 0.01
    big_std: 1

train:
  num_epochs: 20000
  print_epoch_loss: 1
  lr: 1e-2
  batch_size: 16